name: minifier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Minify Action
        uses: dra1ex/minify-action@v1.0.3

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: minified
          create_branch: true
          commit_message: Apply minifications
          repository: /src
